language: go

sudo: required

services:
  - docker

go:
  - "1.11.x"

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/repository/

env:
  - DEP_VERSION="0.5.0"

before_install:
  - sudo apt-get install -y openjdk11-jdk
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v

script:
  - go build
  - cd test && docker-compose up -d && cd ..
  - go test
  - cd integration-test && ./gradlew test --info