version: '3.3'
services:
  fpa:
    image: forward-proxy-auth
    environment: 
      - FPA_AUTHENTICATOR_METHOD=htmlform
      - FPA_SERVER_URI=/fpa
      - FPA_SERVER_PORT=80
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/fpa"
      - "traefik.port=80"
      - "traefik.enable=true"
    networks:
      - default
    env_file:
      - tmpconfig.env
    volumes:
      - ../default-config.yml:/config.yml:ro

  traefik:
    image: traefik:1.7.4
    labels:
      - "traefik.frontend.auth.forward.address=http://fpa/auth"
      - "traefik.frontend.rule=PathPrefixStrip:/traefik"
      - "traefik.port=8080"
      - "traefik.enable=true"
    networks:
     - default    
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
     - "./traefik.toml:/traefik.toml:ro"
    command: -c /traefik.toml
    ports:
      - "80:80"

  whoami:
    image: containous/whoami:v1.0.1
    labels:
      - "traefik.frontend.auth.forward.address=http://fpa/auth"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User,X-Forwarded-Email,X-Forwarded-Groups"
      - "traefik.frontend.rule=PathPrefixStrip:/whoami"
      - "traefik.port=80"
      - "traefik.enable=true"
    networks:
      - default
  
  ldap-test:
    image: rroemhild/test-openldap
    networks:
      - default

  gitea:
    image: gitea/gitea:latest
    labels:
      - "traefik.frontend.auth.forward.address=http://fpa/auth"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User,X-Forwarded-Email,X-Forwarded-Groups,X-WEBAUTH-USER"
      - "traefik.frontend.rule=PathPrefixStrip:/gitea"
      - "traefik.port=3000"
      - "traefik.enable=true"
    environment:
      - ROOT_URL=/gitea
    volumes:
      - "./giteadata:/data"
# following entries must be set in /data/conf/app.ini
#[security]
#REVERSE_PROXY_AUTHENTICATION_USER=X-Forwarded-User
#[service]
#ENABLE_REVERSE_PROXY_AUTHENTICATION=true
#ENABLE_REVERSE_PROXY_AUTO_REGISTRATION=true
